### ISSUE TITLE
64 or 76 pin connector?

### ISSUE THREAD

**Issue by rusefillc** [rusefi/proteus-Honda-OBD1-adapter#1]
@BeerMoneyMotorsports OBD1 uses the same 64 as miata NA and NB1

In your opinion shall we go with 64 as OEM or jump into 76 like on rusEFI NB1 in order to have options port?

**Comment by BeerMoneyMotorsports** [comment]
76 with options

**Comment by rusefillc** [comment]
you got it!

**Comment by BeerMoneyMotorsports** [comment]
We can use nb1 for example

**Comment by rusefillc** [comment]
@BeerMoneyMotorsports huh? you mean copy nb1 options port pinout?

**Comment by BeerMoneyMotorsports** [comment]
Affirmative
